/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://76cvv56upbaarfynamdihjutwm.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3vstrbzr4jafllhrgbyp2zjel4",
    "aws_cognito_identity_pool_id": "ap-south-1:009b1e3a-b596-47a0-b1de-72ed250413e2",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_9i6PblelT",
    "aws_user_pools_web_client_id": "6skoqovvgkks36umrp5cof1k8d",
    "oauth": {}
};


export default awsmobile;
